import React,{useState} from 'react';
import {createRoot} from 'react-dom/client';
import './styles.css';

const TRAIN={id:'12951',name:'Mumbai Rajdhani',from:'New Delhi',to:'Mumbai Central',location:'Kanpur Central',delay:18,additional:15,scheduled:'8:14 PM',eta:'8:47 PM',confidence:82,speed:82,reason:'Low visibility + reduced train speed in this region'};
const RECENT=[TRAIN,{id:'12952',name:'Mumbai Rajdhani',from:'Mumbai Central',to:'New Delhi',location:'Kota Junction',delay:11,additional:7,scheduled:'7:40 PM',eta:'7:58 PM',confidence:78,speed:91,reason:'Moderate congestion near junction'},{id:'12424',name:'New Delhi–Dibrugarh Rajdhani',from:'New Delhi',to:'Dibrugarh',location:'Lucknow',delay:6,additional:3,scheduled:'6:20 PM',eta:'6:29 PM',confidence:89,speed:97,reason:'Normal operating conditions'}];

function Icon({children,className=''}){return <span className={'material-symbols-outlined '+className}>{children}</span>}
function App(){
 const [train,setTrain]=useState(TRAIN),[search,setSearch]=useState(''),[offline,setOffline]=useState(false),[alarmOffset,setAlarmOffset]=useState(10),[alarm,setAlarm]=useState(false),[modal,setModal]=useState(false),[query,setQuery]=useState(''),[messages,setMessages]=useState([{who:'user',text:'Why is 12951 Mumbai Rajdhani delayed, and what is the latest ETA?'},{who:'ai',text:'Train 12951 Mumbai Rajdhani is currently running with a +18 min delay. The model predicts an additional +15 min delay. Latest predicted ETA is 8:47 PM with 82% confidence.'}]),[notices,setNotices]=useState(2),[lang,setLang]=useState('EN'),[showLang,setShowLang]=useState(false),[syncing,setSyncing]=useState(false),[highContrast,setHighContrast]=useState(false);
 const alarmTime=calcAlarm(train.eta,alarmOffset);
 function track(){if(!search.trim()){setSearch('12951');return} const q=search.toLowerCase(); const found=RECENT.find(x=>x.id===search.trim()||x.name.toLowerCase().includes(q)); if(found)setTrain(found); else setTrain({...TRAIN,id:search.trim(),name:'Train Search Result'}); window.scrollTo({top:420,behavior:'smooth'})}
 function simulate(){setTrain(t=>({...t,delay:t.delay+6,additional:t.additional+3,eta:addMinutes(t.eta,9),confidence:Math.max(65,t.confidence-3),reason:'Reduced speed and congestion detected ahead'}));setNotices(n=>n+1)}
 function sync(){setSyncing(true);setTimeout(()=>{setSyncing(false);setOffline(false)},1000)}
 function send(text=query){if(!text.trim())return;setMessages(m=>[...m,{who:'user',text:text.trim()}]);setQuery('');setTimeout(()=>{let r=offline?'Offline cache: Train 12951 was last known near Kanpur Central with +18 min delay. Live AI inference will refresh after reconnection.':text.toLowerCase().includes('platform')?'The latest saved platform information is Platform 1 at Mumbai Central.':text.toLowerCase().includes('weather')||text.toLowerCase().includes('fog')?'Low visibility is contributing to reduced speed. The ETA model currently includes weather and route conditions.':`Latest prediction: ${train.eta}, ${train.delay} min current delay, with ${train.confidence}% confidence. ${train.reason}.`;setMessages(m=>[...m,{who:'ai',text:r}])},450)}
 return <div className={highContrast?'app high-contrast':'app'}>
  <header className="topbar"><div className="navwrap"><div className="brand"><div className="logo"><Icon>train</Icon></div><div><b>DynamicRail</b><small>PRECISION TRANSIT AI</small></div></div><nav><button className="navactive">Home</button><button>My Trains</button><button onClick={()=>setModal(true)}>Notifications <em>{notices}</em></button></nav><div className="controls"><button className={'network '+(offline?'off':'')} onClick={()=>offline?sync():setOffline(true)}><i></i>{offline?'🟠 Offline Mode':'🟢 Live Network'} <span>{syncing?'Syncing…':'↔'}</span></button><div className="lang"><button onClick={()=>setShowLang(!showLang)}>{lang} <Icon>expand_more</Icon></button>{showLang&&<div className="dropdown">{['EN','HI','BN','TA','TE','MR'].map(x=><button key={x} onClick={()=>{setLang(x);setShowLang(false)}}>{x}</button>)}</div>}</div></div></div></header>
  {offline&&<div className="offlinebar"><Icon>wifi_off</Icon> Offline Mode • Last synchronized: 10:42 AM • Saved train information is available • AI Assistant requires internet <button onClick={sync}>Reconnect</button></div>}
  <main>
   <section className="hero"><div className="hero-copy"><div className="eyebrow">AI-POWERED RAILWAY INTELLIGENCE</div><h1>Know where your train is.<br/>Know when it will arrive.</h1><p>Track live running delay and get AI-powered predictions for your train’s arrival.</p><div className="searchbox"><Icon>search</Icon><input value={search} onChange={e=>setSearch(e.target.value)} onKeyDown={e=>e.key==='Enter'&&track()} placeholder="Enter Train Number or Train Name (e.g. 12951 Mumbai Rajdhani)"/><button onClick={track}>Track Train <Icon>arrow_forward</Icon></button></div><div className="hero-tags"><span>Live delay</span><span>Dynamic ETA</span><span>AI prediction</span><span>Smart alarm</span></div></div><div className="train-visual"><div className="glow"></div><div className="train3d"><div className="front"><div className="windshield"></div><div className="light"></div><Icon>train</Icon></div><div className="cars"><i></i><i></i><i></i></div></div><div className="visual-label"><Icon>location_on</Icon><span>LIVE TELEMETRY</span><b>{train.location}</b></div></div></section>
   <section className="update"><div className="update-icon"><Icon>warning</Icon></div><div className="update-body"><div className="row"><h3>Train Delay Prediction Updated</h3><span className="livepill"><i></i>Live Recalibration Active</span></div><div className="transition"><span>Previous predicted ETA:</span><s>8:35 PM</s><Icon>trending_flat</Icon><span>New predicted ETA:</span><strong>{train.eta}</strong><b>(updated)</b></div><p><strong>Expected additional delay:</strong> +{train.additional} min <span>•</span> <strong>Reason:</strong> {train.reason}</p></div><div className="monitor"><span><Icon>sync</Icon> Actively Monitored</span><small>Updated continuously</small></div></section>
   <section className="grid"><article className="card prediction"><div className="cardtop"><div><span className="tag">LIVE TRAIN PREDICTION</span><span className="status"><i></i>Running</span></div><small><Icon>history</Icon> Updated just now</small></div><h2>{train.id} {train.name}</h2><div className="route"><span>{train.from}</span><Icon>arrow_forward</Icon><b>{train.to}</b></div><div className="etaHero"><div><label><Icon>psychology</Icon> AI PREDICTED ETA</label><strong>{train.eta}</strong></div><div className="vs"><b>+{Math.round(train.delay+train.additional)} min vs Schedule</b><small>Timetable: {train.scheduled}</small></div><div className="metric"><span>Current Running Delay</span><b>+{train.delay} min</b></div><div className="metric right"><span>Predicted Additional Delay</span><b>+{train.additional} min</b></div></div><div className="reason"><Icon>report_problem</Icon><span><b>Delay may increase</b> — {train.reason}.</span></div><div className="confidence"><div><span>Prediction Confidence</span><b>{train.confidence}%</b></div><div className="bar"><i style={{width:train.confidence+'%'}}></i></div><small><i></i> Context-aware model</small></div><button className="demo" onClick={simulate}><Icon>autorenew</Icon> Simulate New Live Update</button></article>
   <AlarmCard train={train} offset={alarmOffset} setOffset={setAlarmOffset} alarmTime={alarmTime} alarm={alarm} setAlarm={setAlarm}/></section>
   <section className="routeCard card"><div><span className="tag">ROUTE VISUALIZATION</span><h2>Current journey progress</h2><p>Live position and upcoming stops are kept separate from the prediction engine.</p></div><div className="rail"><div className="station done"><i></i><span>New Delhi</span></div><div className="line"><b style={{width:'58%'}}></b></div><div className="station current"><i></i><span>{train.location}</span><small>Current • {train.speed} km/h</small></div><div className="line"><b></b></div><div className="station"><i></i><span>Vadodara</span></div><div className="line"><b></b></div><div className="station"><i></i><span>{train.to}</span></div></div></section>
   <section className="assistant card"><div className="assistantHead"><div className="aiicon"><Icon>auto_awesome</Icon></div><div><h2>Ask DynamicRail <span>AI ASSISTANT</span></h2><p>Get quick, railway-aware answers about your train.</p></div></div><div className="chips">{['Where is my train?','When will it reach?','Why is my train delayed?','What is the latest ETA?'].map(x=><button key={x} onClick={()=>{setModal(true);setQuery(x)}}>{x}</button>)}</div><div className="ask"><input value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>e.key==='Enter'&&send()} placeholder="Ask about your route, delays, or ETA…"/><button onClick={()=>{setModal(true);send()}}>Ask AI Assistant <Icon>arrow_forward</Icon></button></div></section>
   <section className="recent"><div className="sectiontitle"><h2><Icon>history</Icon> Your Recent Trains</h2><button>Manage</button></div>{RECENT.map((t,i)=><button className="recentCard" key={t.id} onClick={()=>{setTrain(t);window.scrollTo({top:420,behavior:'smooth'})}}><div><b>{t.id} {t.name}</b><span className="delay">+{t.delay} min delay</span><small>{i===0?'On time to next stop':i===1?'In transit':'Normal operations'}</small><p>{t.from} <Icon>arrow_forward</Icon> {t.to}</p></div><div className="recentEta"><label>Predicted ETA</label><strong>{t.eta}</strong><span>View Live Tracker <Icon>chevron_right</Icon></span></div></button>)}</section>
   <section className="features"><div className="sectiontitle center"><div><h2>Built for Precision Transit</h2><p>Passenger-facing intelligence for live railway journeys.</p></div></div><div className="featuregrid">{[['timer','Dynamic ETA Prediction','Continuously recalibrated arrival predictions.'],['speed','Live Running Delay','Current running delay and train movement context.'],['notifications_active','Smart Delay Alerts','Meaningful notifications when ETA changes.'],['alarm','ETA-Based Smart Alarm','Reminders follow the latest available ETA.']].map(f=><div className="feature" key={f[1]}><div><Icon>{f[0]}</Icon></div><h3>{f[1]}</h3><p>{f[2]}</p></div>)}</div></section>
  </main>
  <footer><span>© 2026 DynamicRail • SIH Prototype</span><span>Telemetry latency: 1.2s</span><button onClick={()=>setHighContrast(!highContrast)}><Icon>contrast</Icon> {highContrast?'Normal Contrast':'High Contrast'}</button></footer>
  {modal&&<ChatModal offline={offline} messages={messages} query={query} setQuery={setQuery} send={send} close={()=>setModal(false)} />}
 </div>
}
function AlarmCard({train,offset,setOffset,alarmTime,alarm,setAlarm}){return <article className="card alarm"><div className="alarmHead"><div className="alarmIcon"><Icon>alarm</Icon></div><div><h2>Set Smart Alarm</h2><small>ETA-Adjusting Alarm</small></div><span>ADAPTIVE</span></div><div className="alarmBox"><div><label>Predicted Arrival</label><b>{train.eta}</b></div><div><label>Remind me</label><select value={offset} onChange={e=>setOffset(+e.target.value)}><option value="5">5 minutes before</option><option value="10">10 minutes before</option><option value="15">15 minutes before</option><option value="20">20 minutes before</option><option value="30">30 minutes before</option></select></div><hr/><div className="calculated"><div><label>Calculated Alarm</label><strong>{alarmTime}</strong></div><Icon>schedule</Icon></div><hr/><div className="switchrow"><span>Automatically adjust alarm with ETA</span><button className={'switch '+(alarm?'on':'')} onClick={()=>setAlarm(!alarm)}><i></i></button></div></div><p className="info"><Icon>info</Icon>Your reminder follows the latest available ETA.</p><button className={'alarmbtn '+(alarm?'active':'')} onClick={()=>setAlarm(true)}><Icon>alarm_on</Icon>{alarm?'Smart Alarm Active':'Set Smart Alarm'}</button>{alarm&&<div className="feedback">✓ Smart alarm active for {alarmTime} • auto-adjusting with ETA</div>}</article>}
function ChatModal({offline,messages,query,setQuery,send,close}){return <div className="modal" onMouseDown={e=>e.target===e.currentTarget&&close()}><div className="chat"><header><div className="aiicon"><Icon>psychology</Icon></div><div><h3>DynamicRail Assistant <span>RAIL INTELLIGENCE AI</span></h3><small><i></i>{offline?'Offline • Cached responses':'Online • Live prediction context'}</small></div><button onClick={close}><Icon>close</Icon></button></header>{offline&&<div className="modalwarn"><Icon>cloud_off</Icon> AI Assistant requires internet. Showing cached responses.</div>}<div className="history">{messages.map((m,i)=><div className={'msg '+m.who} key={i}>{m.who==='ai'&&<div className="mini"><Icon>psychology</Icon></div>}<div>{m.text}</div></div>)}</div><div className="quick">{['Platform number?','Weather & fog ahead','Latest ETA?'].map(x=><button key={x} onClick={()=>send(x)}>{x}</button>)}</div><form onSubmit={e=>{e.preventDefault();send()}}><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder="Ask about your train…"/><button>Send <Icon>send</Icon></button></form></div></div>}
function addMinutes(time,n){let [h,rest]=time.split(':');let [m,ampm]=rest.split(' ');let mins=(+h%12)*60+ +m+n;let hh=Math.floor(mins/60)%12||12,mm=String(mins%60).padStart(2,'0');return `${hh}:${mm} ${ampm}`}
function calcAlarm(time,n){return addMinutes(time,-n)}

createRoot(document.getElementById('root')).render(<App/>);
