"""initial_schema

Revision ID: bbccabbfe218
Revises: 
Create Date: 2026-09-11 10:44:55.857887

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

revision = 'bbccabbfe218'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('replay_source',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('train_id', sa.BigInteger(), nullable=False),
    sa.Column('sequence_id', sa.String(length=20), nullable=False),
    sa.Column('sequence_step', sa.Integer(), nullable=False),
    sa.Column('raw_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_replay_source_seq', 'replay_source', ['sequence_id', 'sequence_step'], unique=False)
    op.create_index(op.f('ix_replay_source_train_id'), 'replay_source', ['train_id'], unique=False)
    op.create_table('stations',
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('graph_node_index', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('code'),
    sa.UniqueConstraint('graph_node_index')
    )
    op.create_table('trains',
    sa.Column('train_id', sa.BigInteger(), nullable=False),
    sa.Column('train_name', sa.String(length=255), nullable=False),
    sa.Column('train_type', sa.String(length=32), nullable=False),
    sa.Column('train_category', sa.String(length=32), nullable=False),
    sa.Column('railway_zone', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('train_id')
    )
    op.create_index(op.f('ix_trains_train_name'), 'trains', ['train_name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('preferred_language', sa.String(length=8), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('notification_preferences',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('delay_alerts', sa.Boolean(), nullable=False),
    sa.Column('eta_change_alerts', sa.Boolean(), nullable=False),
    sa.Column('approaching_destination_alerts', sa.Boolean(), nullable=False),
    sa.Column('min_delay_change_threshold_mins', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('route_segments',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('from_station', sa.String(length=10), nullable=False),
    sa.Column('to_station', sa.String(length=10), nullable=False),
    sa.Column('distance_km', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('observed_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['from_station'], ['stations.code'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['to_station'], ['stations.code'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_station', 'to_station')
    )
    op.create_table('routes',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('train_id', sa.BigInteger(), nullable=False),
    sa.Column('origin_station', sa.String(length=10), nullable=True),
    sa.Column('destination_station', sa.String(length=10), nullable=True),
    sa.Column('direction', sa.String(length=4), nullable=True),
    sa.Column('scheduled_distance_km', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('scheduled_journey_time_hrs', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['destination_station'], ['stations.code'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['origin_station'], ['stations.code'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['train_id'], ['trains.train_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routes_train_id'), 'routes', ['train_id'], unique=False)
    op.create_table('smart_alarms',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('train_id', sa.BigInteger(), nullable=False),
    sa.Column('target_station_code', sa.String(length=10), nullable=False),
    sa.Column('offset_minutes', sa.Integer(), nullable=False),
    sa.Column('auto_adjust', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_evaluated_eta', sa.DateTime(timezone=True), nullable=True),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['target_station_code'], ['stations.code'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['train_id'], ['trains.train_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_smart_alarms_train_active', 'smart_alarms', ['train_id', 'is_active'], unique=False)
    op.create_table('tracked_trains',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('train_id', sa.BigInteger(), nullable=False),
    sa.Column('target_station_code', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['target_station_code'], ['stations.code'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['train_id'], ['trains.train_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'train_id')
    )
    op.create_index(op.f('ix_tracked_trains_user_id'), 'tracked_trains', ['user_id'], unique=False)
    op.create_table('train_positions',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('train_id', sa.BigInteger(), nullable=False),
    sa.Column('sequence_id', sa.String(length=20), nullable=True),
    sa.Column('sequence_step', sa.Integer(), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('current_station', sa.String(length=10), nullable=True),
    sa.Column('previous_station', sa.String(length=10), nullable=True),
    sa.Column('next_station', sa.String(length=10), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('current_location_km', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('current_speed_kmh', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('current_delay_mins', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('distance_remaining_km', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('movement_status', sa.String(length=32), nullable=True),
    sa.Column('stoppage_duration_mins', sa.Integer(), nullable=True),
    sa.Column('raw_snapshot', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['current_station'], ['stations.code'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['train_id'], ['trains.train_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_train_positions_train_observed', 'train_positions', ['train_id', 'observed_at'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('train_id', sa.BigInteger(), nullable=False),
    sa.Column('position_id', sa.BigInteger(), nullable=False),
    sa.Column('model_used', sa.String(length=24), nullable=False),
    sa.Column('current_delay_mins', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('predicted_additional_delay_mins', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('predicted_total_delay_mins', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('estimated_remaining_travel_mins', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('eta', sa.DateTime(timezone=True), nullable=False),
    sa.Column('eta_lower', sa.DateTime(timezone=True), nullable=True),
    sa.Column('eta_upper', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delay_reason', sa.Text(), nullable=True),
    sa.Column('delay_reason_confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('propagation_probability', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('propagation_risk', sa.String(length=8), nullable=True),
    sa.Column('ml_metrics_snapshot', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['position_id'], ['train_positions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['train_id'], ['trains.train_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_predictions_train_created', 'predictions', ['train_id', 'created_at'], unique=False)
    op.create_table('route_stations',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('route_id', sa.BigInteger(), nullable=False),
    sa.Column('station_code', sa.String(length=10), nullable=False),
    sa.Column('stop_order', sa.Integer(), nullable=False),
    sa.Column('scheduled_halt_time_mins', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['station_code'], ['stations.code'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('route_id', 'stop_order')
    )
    op.create_index(op.f('ix_route_stations_route_id'), 'route_stations', ['route_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('train_id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('related_prediction_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['related_prediction_id'], ['predictions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['train_id'], ['trains.train_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notifications_user_read_created', 'notifications', ['user_id', 'is_read', 'created_at'], unique=False)
    op.create_table('train_running_status',
    sa.Column('train_id', sa.BigInteger(), nullable=False),
    sa.Column('current_position_id', sa.BigInteger(), nullable=True),
    sa.Column('journey_status', sa.String(length=16), nullable=True),
    sa.Column('last_prediction_id', sa.BigInteger(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['current_position_id'], ['train_positions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['last_prediction_id'], ['predictions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['train_id'], ['trains.train_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('train_id')
    )
    op.create_table('train_schedules',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('train_id', sa.BigInteger(), nullable=False),
    sa.Column('route_id', sa.BigInteger(), nullable=False),
    sa.Column('route_station_id', sa.BigInteger(), nullable=False),
    sa.Column('scheduled_arrival_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_departure_time', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['route_station_id'], ['route_stations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['train_id'], ['trains.train_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_train_schedules_train_id'), 'train_schedules', ['train_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_train_schedules_train_id'), table_name='train_schedules')
    op.drop_table('train_schedules')
    op.drop_table('train_running_status')
    op.drop_index('ix_notifications_user_read_created', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_route_stations_route_id'), table_name='route_stations')
    op.drop_table('route_stations')
    op.drop_index('ix_predictions_train_created', table_name='predictions')
    op.drop_table('predictions')
    op.drop_index('ix_train_positions_train_observed', table_name='train_positions')
    op.drop_table('train_positions')
    op.drop_index(op.f('ix_tracked_trains_user_id'), table_name='tracked_trains')
    op.drop_table('tracked_trains')
    op.drop_index('ix_smart_alarms_train_active', table_name='smart_alarms')
    op.drop_table('smart_alarms')
    op.drop_index(op.f('ix_routes_train_id'), table_name='routes')
    op.drop_table('routes')
    op.drop_table('route_segments')
    op.drop_table('notification_preferences')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_trains_train_name'), table_name='trains')
    op.drop_table('trains')
    op.drop_table('stations')
    op.drop_index(op.f('ix_replay_source_train_id'), table_name='replay_source')
    op.drop_index('ix_replay_source_seq', table_name='replay_source')
    op.drop_table('replay_source')
    # ### end Alembic commands ###
